name: ml4idp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.18
  - matplotlib=3.7.3
  - numpy=1.24.4
  - pandas=2.0.3
  - pandas-stubs=2.1.1.230928
  - scikit-learn=1.3.1
  - scipy=1.10.1
  - seaborn=0.13.0
  - seaborn-base=0.13.0
  - shap=0.43.0
  - shapely=2.0.2
  - pip:
    - plot-metric
